### ISSUE TITLE
enqueue rpc operation is not working

### ISSUE THREAD

**Issue by SnpGroup** [zkSNACKs/WasabiDoc#818] opened 2020-05-09 05:29 UTC
I am testing enqueue rpc operation as per information provided in document

{"jsonrpc":"2.0","id":"1","method":"enqueue", "params": { "coins": [{"transactionId": "ba70587b37ba8b4de143929994d3b8ee2810340cef23e8016020687716117a52", "index":"12"}], "password":"hello"} }

I have replaced txid and pwd as per my requirement, operation is returning success. But nothing is happening at back-end.

please see response below:

{
    "status": true,
    "data": {
          "jsonrpc": "2.0",
          "id": "1"
     },
    "message": ""
}

message is empty and i don't see anything happening.

please check and suggest what is wrong.

**Comment by MaxHillebrand** [comment] 2020-05-09 08:28
As @SnpGroup comments [here](https://github.com/zkSNACKs/WasabiDoc/issues/816#issuecomment-626104765), the issue was because he entered the USD value, not the satoshi value.

**Comment by SnpGroup** [comment] 2020-05-09 09:36
Looks you merged previously reported issue with new issue coming during enqueue operation.

I am following this link for same: https://docs.wasabiwallet.io/using-wasabi/RPC.html#enqueue

I am using this operation to perform coinjoin, it returns status successful but nothing happens.

Please re-open this issue and provide answer for same.

**Comment by MaxHillebrand** [comment] 2020-05-09 12:14
oh sorry, you are right, I got confused...

what's your wasabi version? 
this PR https://github.com/zkSNACKs/WalletWasabi/pull/3550 is merged in v1.1.11.1, this might fix your issue.

**Comment by SnpGroup** [comment] 2020-05-09 12:49
I am using mentioned version only i.e. 1.1.11.1

{"jsonrpc":"2.0","id":"1","method":"enqueue", "params": { "coins": [{"transactionId": "ba70587b37ba8b4de143929994d3b8ee2810340cef23e8016020687716117a52", "index":"12"}], "password":"hello"} }

I am sending valid password as well.

I am getting success in response but nothing happens in backend. I have observed that it reutrns empty message.

**Comment by yahiheb** [comment] 2020-05-09 12:54
Have you replaced the index as well?

**Comment by SnpGroup** [comment] 2020-05-09 12:58
no....i am sending index 12 only......what should go in this field?

**Comment by yahiheb** [comment] 2020-05-09 13:00
It should be the index of the coin you are trying to enqueue.

If you execute https://docs.wasabiwallet.io/using-wasabi/RPC.html#listunspentcoins you should get the list of confirmed and unconfirmed coins that are unspent, and their you should have their index.

**Comment by SnpGroup** [comment] 2020-05-09 13:02
yes....that was the reason.

I changed index value and it worked.

Thanks a lot, you can close this issue.

**Comment by SnpGroup** [comment] 2020-05-09 13:04
one suggestion, when it should return error if something is not matching.

it always returning success and empty message...whether operation successful or failed

**Closed** 2020-05-09 13:08 UTC
